CREATE TABLE `user_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`basePersona` varchar(64),
	`activePersona` varchar(64),
	`agentBundle` text,
	`suggestedWorkflows` text,
	`tone` varchar(64),
	`domainTags` text,
	`queryDomainTags` text,
	`dominantDomain` varchar(64),
	`personaDrift` boolean NOT NULL DEFAULT false,
	`homepageReorder` boolean NOT NULL DEFAULT false,
	`nudgeMessage` text,
	`sessionCount` int NOT NULL DEFAULT 0,
	`agentsUsedList` text,
	`domainTagFrequency` text,
	`workflowsCompleted` text,
	`confidence` enum('HIGH','MEDIUM','LOW') DEFAULT 'HIGH',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `user_profiles_id` PRIMARY KEY(`id`),
	CONSTRAINT `user_profiles_userId_unique` UNIQUE(`userId`)
);
