CREATE TABLE `simulation_fingerprints` (
	`id` int AUTO_INCREMENT NOT NULL,
	`run_id` varchar(64) NOT NULL,
	`deal_id` varchar(64) NOT NULL,
	`deal_name` varchar(255) NOT NULL,
	`council_mode` varchar(64),
	`scenario_count` int NOT NULL,
	`simulation_mode` varchar(32) NOT NULL,
	`approve_pct` float NOT NULL,
	`conditional_pct` float NOT NULL,
	`reject_pct` float NOT NULL,
	`veto_pct` float NOT NULL,
	`rescued_conditional_pct` float NOT NULL,
	`final_rejected_pct` float NOT NULL,
	`attribution_unavailable_pct` float NOT NULL,
	`rescueability_score` float,
	`veto_concentration_score` float,
	`structural_fragility_score` float,
	`scenario_entropy` float,
	`council_disagreement_score` float,
	`council_disagreement_data_unavailable` tinyint NOT NULL DEFAULT 0,
	`dominant_failure_vectors` text,
	`dominant_approval_pathways` text,
	`sensitivity_ranking` text,
	`terminal_flag_frequency` text,
	`governance_escalation_frequency` text,
	`is_upgraded_scenario` tinyint NOT NULL DEFAULT 0,
	`original_run_id` varchar(64),
	`original_verdict` varchar(64),
	`upgraded_verdict` varchar(64),
	`resilience_delta` float,
	`upgrade_effectiveness` float,
	`mitigation_dependency_score` float,
	`source_sector` varchar(128),
	`source_geography` varchar(128),
	`version` varchar(16) NOT NULL DEFAULT '1.0',
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `simulation_fingerprints_id` PRIMARY KEY(`id`),
	CONSTRAINT `simulation_fingerprints_run_id_unique` UNIQUE(`run_id`)
);
--> statement-breakpoint
CREATE INDEX `sfp_run_idx` ON `simulation_fingerprints` (`run_id`);--> statement-breakpoint
CREATE INDEX `sfp_deal_idx` ON `simulation_fingerprints` (`deal_id`);