CREATE TABLE `prospect_configs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(64) NOT NULL,
	`organization_name` varchar(256) NOT NULL,
	`industry` varchar(256) NOT NULL,
	`geography` varchar(128) NOT NULL,
	`tagline` varchar(512),
	`primary_color` varchar(32),
	`accent_color` varchar(32),
	`logo_url` varchar(1024),
	`config_json` text NOT NULL DEFAULT ('{}'),
	`feature_flags` text NOT NULL DEFAULT ('[]'),
	`status` varchar(16) NOT NULL DEFAULT 'DRAFT',
	`version` int NOT NULL DEFAULT 1,
	`version_history` text NOT NULL DEFAULT ('[]'),
	`imported_from_hardcoded` tinyint NOT NULL DEFAULT 0,
	`owner_id` int,
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `prospect_configs_id` PRIMARY KEY(`id`),
	CONSTRAINT `prospect_configs_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `report_templates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`template_id` varchar(64) NOT NULL,
	`name` varchar(256) NOT NULL,
	`description` text,
	`generator_path` varchar(512) NOT NULL,
	`generator_type` varchar(16) NOT NULL DEFAULT 'legacy',
	`status` varchar(16) NOT NULL DEFAULT 'ACTIVE',
	`branding_json` text NOT NULL DEFAULT ('{}'),
	`required_inputs` text NOT NULL DEFAULT ('[]'),
	`supports_page_numbers` tinyint NOT NULL DEFAULT 1,
	`supports_header_footer` tinyint NOT NULL DEFAULT 1,
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `report_templates_id` PRIMARY KEY(`id`),
	CONSTRAINT `report_templates_template_id_unique` UNIQUE(`template_id`)
);
--> statement-breakpoint
CREATE TABLE `twin_parameters` (
	`id` int AUTO_INCREMENT NOT NULL,
	`twin_id` varchar(64) NOT NULL,
	`param_key` varchar(128) NOT NULL,
	`label` varchar(256) NOT NULL,
	`value` text NOT NULL,
	`data_type` varchar(16) NOT NULL DEFAULT 'number',
	`unit` varchar(64),
	`display_unit` varchar(64),
	`min_value` varchar(64),
	`max_value` varchar(64),
	`formula_note` text,
	`source` varchar(512),
	`source_date` varchar(32),
	`confidence` int NOT NULL DEFAULT 80,
	`is_editable` tinyint NOT NULL DEFAULT 1,
	`scenario_overrides` text NOT NULL DEFAULT ('{}'),
	`version` int NOT NULL DEFAULT 1,
	`value_history` text NOT NULL DEFAULT ('[]'),
	`tenant_id` int,
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `twin_parameters_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `workflow_protocol_registry` (
	`id` int AUTO_INCREMENT NOT NULL,
	`protocol_id` varchar(64) NOT NULL,
	`name` varchar(256) NOT NULL,
	`version` varchar(32) NOT NULL DEFAULT '1.0.0',
	`description` text,
	`supported_twin_types` text NOT NULL DEFAULT ('[]'),
	`status` varchar(16) NOT NULL DEFAULT 'DRAFT',
	`tenant_availability` text,
	`config_schema_ref` varchar(512),
	`report_template_ref` varchar(512),
	`agent_count` int NOT NULL DEFAULT 0,
	`estimated_duration_sec` int,
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `workflow_protocol_registry_id` PRIMARY KEY(`id`),
	CONSTRAINT `workflow_protocol_registry_protocol_id_unique` UNIQUE(`protocol_id`)
);
