CREATE TABLE `council_personas` (
	`id` int AUTO_INCREMENT NOT NULL,
	`persona_id` varchar(64) NOT NULL,
	`persona_set_id` varchar(64) NOT NULL,
	`industry_tag` varchar(128) NOT NULL,
	`role` varchar(256) NOT NULL,
	`title` varchar(256) NOT NULL,
	`system_prompt` text NOT NULL,
	`constitution_text` text,
	`vote_weight` int NOT NULL DEFAULT 1,
	`bias_profile` text NOT NULL DEFAULT ('{}'),
	`sort_order` int NOT NULL DEFAULT 0,
	`status` varchar(16) NOT NULL DEFAULT 'ACTIVE',
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `council_personas_id` PRIMARY KEY(`id`),
	CONSTRAINT `council_personas_persona_id_unique` UNIQUE(`persona_id`)
);
--> statement-breakpoint
CREATE TABLE `data_connectors` (
	`id` int AUTO_INCREMENT NOT NULL,
	`connector_id` varchar(64) NOT NULL,
	`name` varchar(256) NOT NULL,
	`connector_type` varchar(32) NOT NULL,
	`description` text,
	`config_schema` text NOT NULL DEFAULT ('{}'),
	`adapter_path` varchar(512),
	`auth_type` varchar(32) NOT NULL DEFAULT 'none',
	`supports_test_connection` tinyint NOT NULL DEFAULT 1,
	`supports_schema_inference` tinyint NOT NULL DEFAULT 0,
	`supports_streaming` tinyint NOT NULL DEFAULT 0,
	`max_rows_per_sync` int NOT NULL DEFAULT 10000,
	`status` varchar(16) NOT NULL DEFAULT 'ACTIVE',
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `data_connectors_id` PRIMARY KEY(`id`),
	CONSTRAINT `data_connectors_connector_id_unique` UNIQUE(`connector_id`)
);
--> statement-breakpoint
CREATE TABLE `decision_types` (
	`id` int AUTO_INCREMENT NOT NULL,
	`decision_type_id` varchar(64) NOT NULL,
	`name` varchar(256) NOT NULL,
	`category` varchar(128) NOT NULL,
	`description` text,
	`default_council_persona_set_id` varchar(64),
	`default_kpi_set_id` varchar(64),
	`default_simulation_mode` varchar(32) NOT NULL DEFAULT 'institutional',
	`evaluation_framework` text NOT NULL DEFAULT ('{}'),
	`required_input_fields` text NOT NULL DEFAULT ('[]'),
	`output_schema` text NOT NULL DEFAULT ('{}'),
	`industry_tags` text NOT NULL DEFAULT ('[]'),
	`status` varchar(16) NOT NULL DEFAULT 'ACTIVE',
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `decision_types_id` PRIMARY KEY(`id`),
	CONSTRAINT `decision_types_decision_type_id_unique` UNIQUE(`decision_type_id`)
);
--> statement-breakpoint
CREATE TABLE `domain_ontologies` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ontology_id` varchar(64) NOT NULL,
	`name` varchar(256) NOT NULL,
	`industry_tag` varchar(128) NOT NULL,
	`version` varchar(16) NOT NULL DEFAULT '1.0.0',
	`entities` text NOT NULL DEFAULT ('[]'),
	`relationships` text NOT NULL DEFAULT ('[]'),
	`terminology` text NOT NULL DEFAULT ('{}'),
	`regulatory_context` text NOT NULL DEFAULT ('{}'),
	`geographic_context` text NOT NULL DEFAULT ('{}'),
	`system_prompt_fragment` text,
	`evaluation_criteria` text,
	`status` varchar(16) NOT NULL DEFAULT 'ACTIVE',
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `domain_ontologies_id` PRIMARY KEY(`id`),
	CONSTRAINT `domain_ontologies_ontology_id_unique` UNIQUE(`ontology_id`)
);
--> statement-breakpoint
CREATE TABLE `kpi_definitions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`kpi_id` varchar(64) NOT NULL,
	`kpi_set_id` varchar(64) NOT NULL,
	`industry_tag` varchar(128) NOT NULL,
	`name` varchar(256) NOT NULL,
	`label` varchar(256) NOT NULL,
	`unit` varchar(64),
	`direction` varchar(16) NOT NULL DEFAULT 'higher',
	`threshold` text NOT NULL DEFAULT ('{}'),
	`benchmark_source` varchar(512),
	`description` text,
	`formula` text,
	`category` varchar(128),
	`sort_order` int NOT NULL DEFAULT 0,
	`status` varchar(16) NOT NULL DEFAULT 'ACTIVE',
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `kpi_definitions_id` PRIMARY KEY(`id`),
	CONSTRAINT `kpi_definitions_kpi_id_unique` UNIQUE(`kpi_id`)
);
--> statement-breakpoint
CREATE TABLE `report_registry` (
	`id` int AUTO_INCREMENT NOT NULL,
	`report_type_id` varchar(64) NOT NULL,
	`name` varchar(256) NOT NULL,
	`description` text,
	`category` varchar(128) NOT NULL DEFAULT 'general',
	`output_format` varchar(16) NOT NULL DEFAULT 'pdf',
	`template_schema` text NOT NULL DEFAULT ('{}'),
	`required_sections` text NOT NULL DEFAULT ('[]'),
	`optional_sections` text NOT NULL DEFAULT ('[]'),
	`branding_defaults` text NOT NULL DEFAULT ('{}'),
	`industry_tags` text NOT NULL DEFAULT ('[]'),
	`generator_type` varchar(32) NOT NULL DEFAULT 'template',
	`legacy_generator_path` varchar(512),
	`status` varchar(16) NOT NULL DEFAULT 'ACTIVE',
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `report_registry_id` PRIMARY KEY(`id`),
	CONSTRAINT `report_registry_report_type_id_unique` UNIQUE(`report_type_id`)
);
--> statement-breakpoint
CREATE TABLE `simulation_plugins` (
	`id` int AUTO_INCREMENT NOT NULL,
	`plugin_id` varchar(64) NOT NULL,
	`name` varchar(256) NOT NULL,
	`description` text,
	`category` varchar(128) NOT NULL DEFAULT 'stress_test',
	`engine_type` varchar(64) NOT NULL DEFAULT 'perturbation',
	`config_schema` text NOT NULL DEFAULT ('{}'),
	`default_config` text NOT NULL DEFAULT ('{}'),
	`max_scenario_count` int NOT NULL DEFAULT 1000,
	`cost_tier` varchar(16) NOT NULL DEFAULT 'medium',
	`requires_confirmation` tinyint NOT NULL DEFAULT 0,
	`industry_tags` text NOT NULL DEFAULT ('[]'),
	`status` varchar(16) NOT NULL DEFAULT 'ACTIVE',
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `simulation_plugins_id` PRIMARY KEY(`id`),
	CONSTRAINT `simulation_plugins_plugin_id_unique` UNIQUE(`plugin_id`)
);
--> statement-breakpoint
CREATE TABLE `twin_blueprints` (
	`id` int AUTO_INCREMENT NOT NULL,
	`blueprint_id` varchar(64) NOT NULL,
	`name` varchar(256) NOT NULL,
	`slug` varchar(64) NOT NULL,
	`industry` varchar(128) NOT NULL,
	`organization_type` varchar(128),
	`description` text,
	`ontology_id` varchar(64),
	`default_council_persona_set_id` varchar(64),
	`default_decision_type_ids` text NOT NULL DEFAULT ('[]'),
	`default_kpi_set_id` varchar(64),
	`default_simulation_mode` varchar(32) NOT NULL DEFAULT 'institutional',
	`default_report_template_ids` text NOT NULL DEFAULT ('[]'),
	`default_workflow_protocol_id` varchar(64),
	`governance_profile_id` varchar(64),
	`security_profile` varchar(32) NOT NULL DEFAULT 'standard',
	`primary_color` varchar(16) NOT NULL DEFAULT '#3b82f6',
	`accent_color` varchar(16) NOT NULL DEFAULT '#f59e0b',
	`logo_url` varchar(512),
	`ui_theme` varchar(32) NOT NULL DEFAULT 'dark',
	`executive_dashboard_layout` text NOT NULL DEFAULT ('{}'),
	`prompt_templates` text NOT NULL DEFAULT ('{}'),
	`status` varchar(16) NOT NULL DEFAULT 'ACTIVE',
	`version` varchar(16) NOT NULL DEFAULT '1.0.0',
	`parent_blueprint_id` varchar(64),
	`created_by` int,
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `twin_blueprints_id` PRIMARY KEY(`id`),
	CONSTRAINT `twin_blueprints_blueprint_id_unique` UNIQUE(`blueprint_id`),
	CONSTRAINT `twin_blueprints_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `twin_compositions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`composition_id` varchar(64) NOT NULL,
	`name` varchar(256) NOT NULL,
	`description` text,
	`component_blueprint_ids` text NOT NULL DEFAULT ('[]'),
	`conflict_resolution_strategy` varchar(32) NOT NULL DEFAULT 'union',
	`council_merge_strategy` varchar(32) NOT NULL DEFAULT 'weighted',
	`kpi_aggregation_strategy` varchar(32) NOT NULL DEFAULT 'weighted_avg',
	`output_blueprint_id` varchar(64),
	`composition_schema` text NOT NULL DEFAULT ('{}'),
	`status` varchar(16) NOT NULL DEFAULT 'DRAFT',
	`created_by` int,
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `twin_compositions_id` PRIMARY KEY(`id`),
	CONSTRAINT `twin_compositions_composition_id_unique` UNIQUE(`composition_id`)
);
