/**
 * boardPackExport.ts — Board Intelligence Pack Export Engine
 *
 * Generates board-quality documents in three formats:
 *   - PDF  (pdfkit)
 *   - PPTX (pptxgenjs)
 *   - DOCX (docx)
 *
 * Every document is designed to be handed directly to a chairman, CEO,
 * or investment committee without additional editing.
 */

import type { BoardPackData, BoardPackSection } from "./routers/aros/boardPack";

// ── Colour palette (shared across formats) ────────────────────────────────────
const NAVY = "#0B1629";
const GOLD = "#C9A84C";
const WHITE = "#FFFFFF";
const LIGHT_GRAY = "#F1F5F9";
const MID_GRAY = "#94A3B8";
const DARK_TEXT = "#1E293B";
const ACCENT_BLUE = "#3B82F6";

// ── Helpers ───────────────────────────────────────────────────────────────────

function stripMarkdown(md: string): string {
  return md
    .replace(/#{1,6}\s+/g, "")
    .replace(/\*\*(.*?)\*\*/g, "$1")
    .replace(/\*(.*?)\*/g, "$1")
    .replace(/`(.*?)`/g, "$1")
    .replace(/^[-*]\s+/gm, "• ")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

function parseMarkdownSections(md: string): { heading: string; body: string }[] {
  const lines = md.split("\n");
  const sections: { heading: string; body: string }[] = [];
  let current: { heading: string; lines: string[] } | null = null;

  for (const line of lines) {
    const h2 = line.match(/^##\s+(.+)/);
    const h3 = line.match(/^###\s+(.+)/);
    if (h2 || h3) {
      if (current) sections.push({ heading: current.heading, body: current.lines.join("\n").trim() });
      current = { heading: (h2 ?? h3)![1], lines: [] };
    } else if (current) {
      current.lines.push(line);
    }
  }
  if (current) sections.push({ heading: current.heading, body: current.lines.join("\n").trim() });
  return sections;
}

// ── PDF Export ────────────────────────────────────────────────────────────────

export async function generateBoardPackPdf(pack: BoardPackData): Promise<Buffer> {
  const PDFDocument = (await import("pdfkit")).default;

  return new Promise<Buffer>((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margin: 56,
      bufferPages: true,
      info: {
        Title: `Board Intelligence Pack — ${pack.companyName}`,
        Author: "Atlas by AgenThink Mesh",
        Subject: "Board Intelligence Pack",
        Keywords: "board, intelligence, decision twin, atlas",
      },
    });

    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const pageW = doc.page.width - 112; // usable width
    const LEFT = 56;

    // ── Cover page ────────────────────────────────────────────────────────────
    // Dark background
    doc.rect(0, 0, doc.page.width, doc.page.height).fill(NAVY);

    // Gold accent bar
    doc.rect(0, 0, 6, doc.page.height).fill(GOLD);

    // AgenThink Mesh label
    doc.fillColor(GOLD).fontSize(9).font("Helvetica")
      .text("AGENTHINK MESH · ATLAS INTELLIGENCE SYSTEM", LEFT + 10, 56, { characterSpacing: 2 });

    // Title
    doc.fillColor(WHITE).fontSize(28).font("Helvetica-Bold")
      .text("Board Intelligence Pack", LEFT + 10, 120, { width: pageW - 10 });

    // Company name
    doc.fillColor(GOLD).fontSize(20).font("Helvetica")
      .text(pack.companyName, LEFT + 10, 164, { width: pageW - 10 });

    // Executive
    if (pack.executiveName) {
      doc.fillColor(MID_GRAY).fontSize(13).font("Helvetica")
        .text(`Attention: ${pack.executiveName}`, LEFT + 10, 196, { width: pageW - 10 });
    }

    // Divider
    doc.moveTo(LEFT + 10, 230).lineTo(LEFT + 10 + 200, 230).strokeColor(GOLD).lineWidth(1).stroke();

    // Generation info
    doc.fillColor(MID_GRAY).fontSize(9).font("Helvetica")
      .text(`Generated: ${new Date(pack.generatedAt).toUTCString()}`, LEFT + 10, 244)
      .text(`Constitution Version: ${pack.constitutionVersion}`, LEFT + 10, 258)
      .text(`Pack ID: ${pack.packId}`, LEFT + 10, 272)
      .text(`Model: ${pack.modelVersion}`, LEFT + 10, 286);

    // Confidentiality notice
    doc.fillColor(MID_GRAY).fontSize(8).font("Helvetica-Oblique")
      .text(
        "CONFIDENTIAL — This document contains proprietary intelligence generated by Atlas. It is intended solely for the named recipient and must not be reproduced or distributed without authorisation.",
        LEFT + 10, doc.page.height - 100,
        { width: pageW - 10, align: "center" }
      );

    // Section index
    doc.fillColor(WHITE).fontSize(10).font("Helvetica-Bold")
      .text("Contents", LEFT + 10, 330);
    pack.sections.forEach((s, i) => {
      doc.fillColor(MID_GRAY).fontSize(9).font("Helvetica")
        .text(`${i + 1}.  ${s.title}`, LEFT + 20, 350 + i * 16);
    });

    // ── Section pages ─────────────────────────────────────────────────────────
    pack.sections.forEach((section, idx) => {
      doc.addPage();

      // Section header bar
      doc.rect(0, 0, doc.page.width, 48).fill(NAVY);
      doc.rect(0, 0, 6, 48).fill(GOLD);

      // Section number + title
      doc.fillColor(GOLD).fontSize(8).font("Helvetica")
        .text(`SECTION ${idx + 1}`, LEFT + 10, 12, { characterSpacing: 1.5 });
      doc.fillColor(WHITE).fontSize(15).font("Helvetica-Bold")
        .text(section.title.toUpperCase(), LEFT + 10, 24);

      // Company name (top right)
      doc.fillColor(MID_GRAY).fontSize(8).font("Helvetica")
        .text(pack.companyName, LEFT + 10, 12, { width: pageW - 10, align: "right" });

      // Body
      const bodyY = 68;
      const bodyText = stripMarkdown(section.content);

      // Parse sub-sections
      const subSections = parseMarkdownSections(section.content);

      if (subSections.length > 0) {
        let y = bodyY;
        for (const sub of subSections) {
          if (y > doc.page.height - 100) { doc.addPage(); y = 56; }
          // Sub-heading
          doc.fillColor(ACCENT_BLUE).fontSize(10).font("Helvetica-Bold")
            .text(sub.heading, LEFT, y, { width: pageW });
          y += 18;
          // Body text
          const bodyLines = stripMarkdown(sub.body);
          if (bodyLines) {
            doc.fillColor(DARK_TEXT).fontSize(9).font("Helvetica")
              .text(bodyLines, LEFT, y, { width: pageW, lineGap: 3 });
            y = doc.y + 14;
          }
        }
      } else {
        doc.fillColor(DARK_TEXT).fontSize(9.5).font("Helvetica")
          .text(bodyText, LEFT, bodyY, { width: pageW, lineGap: 4 });
      }

      // Footer
      doc.fillColor(MID_GRAY).fontSize(7.5).font("Helvetica")
        .text(
          `Atlas Board Intelligence Pack · ${pack.companyName} · Confidential · Page ${idx + 2}`,
          LEFT, doc.page.height - 36, { width: pageW, align: "center" }
        );
    });

    // ── Final audit page ──────────────────────────────────────────────────────
    doc.addPage();
    doc.rect(0, 0, doc.page.width, doc.page.height).fill(NAVY);
    doc.rect(0, 0, 6, doc.page.height).fill(GOLD);

    doc.fillColor(GOLD).fontSize(9).font("Helvetica")
      .text("ATLAS INTELLIGENCE SYSTEM", LEFT + 10, 56, { characterSpacing: 2 });
    doc.fillColor(WHITE).fontSize(16).font("Helvetica-Bold")
      .text("Verification & Integrity Statement", LEFT + 10, 80);

    doc.fillColor(MID_GRAY).fontSize(9).font("Helvetica")
      .text(
        "This Board Intelligence Pack was generated by Atlas using only verified operational data sourced from the Atlas Outcome Ledger, Decision Twin database, and Constitution-governed generation pipeline. No simulated performance data was used. Every metric is derived from real outcomes recorded in the Atlas system.",
        LEFT + 10, 116, { width: pageW - 10, lineGap: 4 }
      );

    const auditItems = [
      ["Pack ID", pack.packId],
      ["Company", pack.companyName],
      ["Generated", new Date(pack.generatedAt).toISOString()],
      ["Constitution Version", pack.constitutionVersion],
      ["Model Version", pack.modelVersion],
      ["Decision Twin Version", pack.auditTrail.decisionTwinVersion],
      ["Hidden Variable Version", pack.auditTrail.hiddenVariableVersion],
      ["Evidence Manifest Hash", pack.auditTrail.evidenceManifestHash ?? "Not available"],
    ];

    let ay = 200;
    for (const [k, v] of auditItems) {
      doc.fillColor(GOLD).fontSize(8).font("Helvetica-Bold").text(k, LEFT + 10, ay);
      doc.fillColor(WHITE).fontSize(8).font("Helvetica").text(String(v), LEFT + 160, ay);
      ay += 18;
    }

    doc.end();
  });
}

// ── PPTX Export ───────────────────────────────────────────────────────────────

export async function generateBoardPackPptx(pack: BoardPackData): Promise<Buffer> {
  const PptxGenJS = (await import("pptxgenjs")).default;
  const prs = new PptxGenJS();

  prs.layout = "LAYOUT_WIDE";
  prs.title = `Board Intelligence Pack — ${pack.companyName}`;
  prs.subject = "Atlas Board Intelligence Pack";
  prs.author = "Atlas by AgenThink Mesh";

  const NAVY_HEX = "0B1629";
  const GOLD_HEX = "C9A84C";
  const WHITE_HEX = "FFFFFF";
  const GRAY_HEX = "94A3B8";
  const BLUE_HEX = "3B82F6";

  // ── Cover slide ───────────────────────────────────────────────────────────
  const cover = prs.addSlide();
  cover.background = { color: NAVY_HEX };
  cover.addShape("rect" as never, { x: 0, y: 0, w: 0.08, h: "100%", fill: { color: GOLD_HEX }, line: { color: GOLD_HEX } });
  cover.addText("AGENTHINK MESH · ATLAS INTELLIGENCE SYSTEM", {
    x: 0.4, y: 0.4, w: 12, h: 0.3,
    fontSize: 8, color: GOLD_HEX, bold: false, charSpacing: 2, fontFace: "Calibri",
  });
  cover.addText("Board Intelligence Pack", {
    x: 0.4, y: 1.0, w: 12, h: 0.8,
    fontSize: 32, color: WHITE_HEX, bold: true, fontFace: "Calibri",
  });
  cover.addText(pack.companyName, {
    x: 0.4, y: 1.9, w: 12, h: 0.5,
    fontSize: 22, color: GOLD_HEX, bold: false, fontFace: "Calibri",
  });
  if (pack.executiveName) {
    cover.addText(`Attention: ${pack.executiveName}`, {
      x: 0.4, y: 2.5, w: 12, h: 0.35,
      fontSize: 13, color: GRAY_HEX, fontFace: "Calibri",
    });
  }
  cover.addShape("line" as never, { x: 0.4, y: 3.1, w: 3, h: 0, line: { color: GOLD_HEX, width: 1 } });
  cover.addText([
    { text: `Generated: `, options: { color: GRAY_HEX, fontSize: 9 } },
    { text: new Date(pack.generatedAt).toUTCString(), options: { color: WHITE_HEX, fontSize: 9 } },
  ], { x: 0.4, y: 3.3, w: 12, h: 0.25, fontFace: "Calibri" });
  cover.addText([
    { text: `Constitution: `, options: { color: GRAY_HEX, fontSize: 9 } },
    { text: pack.constitutionVersion, options: { color: WHITE_HEX, fontSize: 9 } },
  ], { x: 0.4, y: 3.6, w: 12, h: 0.25, fontFace: "Calibri" });
  cover.addText([
    { text: `Pack ID: `, options: { color: GRAY_HEX, fontSize: 9 } },
    { text: pack.packId, options: { color: WHITE_HEX, fontSize: 9 } },
  ], { x: 0.4, y: 3.9, w: 12, h: 0.25, fontFace: "Calibri" });

  // Contents slide
  const contents = prs.addSlide();
  contents.background = { color: NAVY_HEX };
  contents.addShape("rect" as never, { x: 0, y: 0, w: 0.08, h: "100%", fill: { color: GOLD_HEX }, line: { color: GOLD_HEX } });
  contents.addText("CONTENTS", { x: 0.4, y: 0.3, w: 12, h: 0.35, fontSize: 10, color: GOLD_HEX, charSpacing: 2, fontFace: "Calibri" });
  const contentRows = pack.sections.map((s, i) => ({
    text: `${i + 1}.  ${s.title}`,
    options: { color: WHITE_HEX, fontSize: 13, fontFace: "Calibri" },
  }));
  contents.addText(contentRows, { x: 0.4, y: 0.9, w: 12, h: 5.5, paraSpaceAfter: 10 });

  // ── Section slides ─────────────────────────────────────────────────────────
  pack.sections.forEach((section, idx) => {
    const slide = prs.addSlide();
    slide.background = { color: "F8FAFC" };

    // Header bar
    slide.addShape("rect" as never, { x: 0, y: 0, w: "100%", h: 0.65, fill: { color: NAVY_HEX }, line: { color: NAVY_HEX } });
    slide.addShape("rect" as never, { x: 0, y: 0, w: 0.08, h: 0.65, fill: { color: GOLD_HEX }, line: { color: GOLD_HEX } });
    slide.addText(`SECTION ${idx + 1}`, {
      x: 0.3, y: 0.05, w: 8, h: 0.25,
      fontSize: 7, color: GOLD_HEX, charSpacing: 1.5, fontFace: "Calibri",
    });
    slide.addText(section.title.toUpperCase(), {
      x: 0.3, y: 0.3, w: 8, h: 0.3,
      fontSize: 14, color: WHITE_HEX, bold: true, fontFace: "Calibri",
    });
    slide.addText(pack.companyName, {
      x: 8, y: 0.2, w: 5, h: 0.3,
      fontSize: 9, color: GRAY_HEX, align: "right", fontFace: "Calibri",
    });

    // Body — parse sub-sections for structured display
    const subSections = parseMarkdownSections(section.content);
    if (subSections.length > 0) {
      const textParts: { text: string; options?: Record<string, unknown> }[] = [];
      for (const sub of subSections) {
        textParts.push({ text: `${sub.heading}\n`, options: { color: BLUE_HEX, bold: true, fontSize: 10, fontFace: "Calibri", breakLine: false } });
        const bodyText = stripMarkdown(sub.body);
        if (bodyText) {
          textParts.push({ text: `${bodyText}\n\n`, options: { color: DARK_TEXT.replace("#", ""), bold: false, fontSize: 9, fontFace: "Calibri", breakLine: false } });
        }
      }
      slide.addText(textParts, { x: 0.3, y: 0.85, w: 12.7, h: 6.0, valign: "top", wrap: true });
    } else {
      const bodyText = stripMarkdown(section.content);
      slide.addText(bodyText, {
        x: 0.3, y: 0.85, w: 12.7, h: 6.0,
        fontSize: 9.5, color: DARK_TEXT.replace("#", ""), fontFace: "Calibri",
        valign: "top", wrap: true, lineSpacingMultiple: 1.4,
      });
    }

    // Footer
    slide.addShape("line" as never, { x: 0, y: 7.2, w: "100%", h: 0, line: { color: NAVY_HEX, width: 0.5 } });
    slide.addText(`Atlas Board Intelligence Pack · ${pack.companyName} · Confidential · ${idx + 2}`, {
      x: 0, y: 7.25, w: "100%", h: 0.2,
      fontSize: 7, color: GRAY_HEX, align: "center", fontFace: "Calibri",
    });
  });

  const data = await prs.write({ outputType: "nodebuffer" });
  return data as Buffer;
}

// ── DOCX Export ───────────────────────────────────────────────────────────────

export async function generateBoardPackDocx(pack: BoardPackData): Promise<Buffer> {
  const {
    Document, Packer, Paragraph, TextRun, HeadingLevel,
    AlignmentType, BorderStyle, ShadingType, Header,
    Footer, PageNumber, NumberFormat, TableOfContents,
  } = await import("docx");

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const children: any[] = [];

  // ── Cover ─────────────────────────────────────────────────────────────────
  children.push(
    new Paragraph({
      children: [new TextRun({ text: "AGENTHINK MESH · ATLAS INTELLIGENCE SYSTEM", color: "C9A84C", size: 18, characterSpacing: 200 })],
      spacing: { before: 400, after: 200 },
    }),
    new Paragraph({
      text: "Board Intelligence Pack",
      heading: HeadingLevel.TITLE,
      spacing: { before: 200, after: 200 },
    }),
    new Paragraph({
      children: [new TextRun({ text: pack.companyName, color: "C9A84C", size: 44, bold: true })],
      spacing: { before: 100, after: 200 },
    }),
  );

  if (pack.executiveName) {
    children.push(
      new Paragraph({
        children: [new TextRun({ text: `Attention: ${pack.executiveName}`, color: "64748B", size: 26 })],
        spacing: { after: 300 },
      })
    );
  }

  children.push(
    new Paragraph({
      children: [new TextRun({ text: `Generated: ${new Date(pack.generatedAt).toUTCString()}`, size: 18, color: "64748B" })],
    }),
    new Paragraph({
      children: [new TextRun({ text: `Constitution Version: ${pack.constitutionVersion}`, size: 18, color: "64748B" })],
    }),
    new Paragraph({
      children: [new TextRun({ text: `Pack ID: ${pack.packId}`, size: 18, color: "64748B" })],
    }),
    new Paragraph({
      children: [new TextRun({ text: `Model: ${pack.modelVersion}`, size: 18, color: "64748B" })],
      spacing: { after: 600 },
    }),
    new Paragraph({
      children: [new TextRun({
        text: "CONFIDENTIAL — This document contains proprietary intelligence generated by Atlas. It is intended solely for the named recipient and must not be reproduced or distributed without authorisation.",
        italics: true, color: "94A3B8", size: 16,
      })],
      spacing: { after: 800 },
    }),
  );

  // ── Sections ──────────────────────────────────────────────────────────────
  pack.sections.forEach((section, idx) => {
    // Section heading
    children.push(
      new Paragraph({
        children: [
          new TextRun({ text: `Section ${idx + 1} — `, color: "C9A84C", size: 28, bold: true }),
          new TextRun({ text: section.title, size: 28, bold: true }),
        ],
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 600, after: 200 },
        border: {
          bottom: { style: BorderStyle.SINGLE, size: 6, color: "C9A84C" },
        },
      })
    );

    // Parse sub-sections
    const subSections = parseMarkdownSections(section.content);
    if (subSections.length > 0) {
      for (const sub of subSections) {
        children.push(
          new Paragraph({
            children: [new TextRun({ text: sub.heading, color: "3B82F6", size: 22, bold: true })],
            heading: HeadingLevel.HEADING_2,
            spacing: { before: 300, after: 100 },
          })
        );
        const bodyLines = stripMarkdown(sub.body).split("\n");
        for (const line of bodyLines) {
          if (!line.trim()) continue;
          const isBullet = line.startsWith("• ");
          children.push(
            new Paragraph({
              children: [new TextRun({ text: isBullet ? line.slice(2) : line, size: 20 })],
              bullet: isBullet ? { level: 0 } : undefined,
              spacing: { after: 80 },
            })
          );
        }
      }
    } else {
      const bodyLines = stripMarkdown(section.content).split("\n");
      for (const line of bodyLines) {
        if (!line.trim()) continue;
        const isBullet = line.startsWith("• ");
        children.push(
          new Paragraph({
            children: [new TextRun({ text: isBullet ? line.slice(2) : line, size: 20 })],
            bullet: isBullet ? { level: 0 } : undefined,
            spacing: { after: 80 },
          })
        );
      }
    }
  });

  // ── Audit footer ──────────────────────────────────────────────────────────
  children.push(
    new Paragraph({
      children: [new TextRun({ text: "Verification & Integrity Statement", color: "C9A84C", size: 28, bold: true })],
      heading: HeadingLevel.HEADING_1,
      spacing: { before: 600, after: 200 },
    }),
    new Paragraph({
      children: [new TextRun({
        text: "This Board Intelligence Pack was generated by Atlas using only verified operational data. No simulated performance data was used. Every metric is derived from real outcomes recorded in the Atlas system.",
        italics: true, size: 18, color: "64748B",
      })],
      spacing: { after: 200 },
    }),
  );

  const doc = new Document({
    title: `Board Intelligence Pack — ${pack.companyName}`,
    description: "Generated by Atlas, AgenThink Mesh",
    creator: "Atlas Intelligence System",
    sections: [{
      properties: {
        page: {
          margin: { top: 1134, bottom: 1134, left: 1134, right: 1134 },
        },
      },
      headers: {
        default: new Header({
          children: [
            new Paragraph({
              children: [
                new TextRun({ text: "AGENTHINK MESH · ATLAS INTELLIGENCE SYSTEM", color: "C9A84C", size: 14, characterSpacing: 100 }),
                new TextRun({ text: "   |   ", color: "94A3B8", size: 14 }),
                new TextRun({ text: pack.companyName, size: 14, bold: true }),
                new TextRun({ text: "   |   CONFIDENTIAL", color: "94A3B8", size: 14 }),
              ],
              alignment: AlignmentType.RIGHT,
            }),
          ],
        }),
      },
      footers: {
        default: new Footer({
          children: [
            new Paragraph({
              children: [
                new TextRun({ text: "Board Intelligence Pack · ", size: 14, color: "94A3B8" }),
                new TextRun({ text: `Pack ID: ${pack.packId.slice(0, 8)}… · `, size: 14, color: "94A3B8" }),
                new TextRun({ text: "Page ", size: 14, color: "94A3B8" }),
                new TextRun({ children: [PageNumber.CURRENT], size: 14, color: "94A3B8" }),
                new TextRun({ text: " of ", size: 14, color: "94A3B8" }),
                new TextRun({ children: [PageNumber.TOTAL_PAGES], size: 14, color: "94A3B8" }),
              ],
              alignment: AlignmentType.CENTER,
            }),
          ],
        }),
      },
      children,
    }],
    numbering: {
      config: [{
        reference: "default-bullet",
        levels: [{
          level: 0,
          format: NumberFormat.BULLET,
          text: "•",
          alignment: AlignmentType.LEFT,
          style: { paragraph: { indent: { left: 720, hanging: 260 } } },
        }],
      }],
    },
  });

  return Packer.toBuffer(doc);
}
